services:
  - type: web
    name: podc-chatbot-backend-test1
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: OPENAI_API_KEY
        sync: false

  - type: static
    name: podc-chatbot-frontend-test1
    buildCommand: echo "No build step needed"
    staticPublishPath: frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html